name: Go Package Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.5'

      - name: Install dependencies
        run: go mod download

      - name: Build and test
        run: go build -o mtm cli/cli.go
        env:
          GOOS: linux
          GOARCH: amd64
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        # if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          name: mtm
          workdir: ./cli/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}