name: Go Package Build and Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.21.5'

      - name: Install dependencies
        run: go mod download

      - name: Build and test
        run: go build -o mtm cli/cli.go
        env:
          GOOS: linux
          GOARCH: amd64

      - name: Publish to GitHub Packages
        uses: github/codeql-action/publish@v1
        with:
          package-name: krishnaduttPanchagnula/medium-to-markdown-go
          package-version: ${{ github.sha }}
          package-architecture: linux-amd64
          package-os: linux